name: Duas Americas Group, Inc
type: Corporation;
description: Duas Americas Group, Inc is an American Multinational Corporation that provides business consulting, information technology, and outsourcing services.
CEO: Aslan Varoqua
COO: Daniel Vieira
CSO: Dawn Clark-Montenegro
logo :
  image: "../css/2016_style/img/logos/aslan-varoqua-greenblue-duas-logo.png" 
  url: "http://duasamericasgroup.com"

title: Duas Americas Group, Inc
url: "http://duasamericasgroup.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/logos/aslan-varoqua-greenblue-duas-logo.png"

social: 
  name: DUAS AMERICAS | A Digital Agency | Aslan Varoqua & Daniel Vieira
  link: "https://www.facebook.com/duasamericasgroup"

image: "../css/2016_style/img/logos/aslan-varoqua-greenblue-duas-logo.png"


google_site_verification: google39cf25423549c9c.html

include: ['_2016_pages', '_2017_pages']

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/duasamericasgroup
  - title: twitter
    url: https://twitter.com/duasamericasgroup
  - title: instagram
    url: https://instagram.com/duasamericasgroup

# Build settings
markdown: kramdown
permalink: pretty
